### ISSUE TITLE
doesn't work at all lol

### ISSUE THREAD

**Issue by trickmint** [Vendicated/PowercordReacter#5]
every time i try to use .react it just displays an error of "An error occurred while executing the command: Cannot read property 'type' of null.
Check the console for more details."

**Comment by SheepCommander** [comment]
Still doesn't work, for more information
```md
VM1067 C:\Users\sheep\powercord\src\Powercord\plugins\pc-commands\monkeypatchMessages.js:32 An error occurred while executing command react: TypeError: Cannot read property 'type' of undefined
    at Reacter.canReact (C:\Users\sheep\powercord\src\Powercord\plugins\PowercordReacter\index.js:123:15)
    at Reacter.run (C:\Users\sheep\powercord\src\Powercord\plugins\PowercordReacter\index.js:36:15)
    at Object.messages.sendMessage.oldSendMessage [as sendMessage] (C:\Users\sheep\powercord\src\Powercord\plugins\pc-commands\monkeypatchMessages.js:25:30)
```

**Comment by he3als** [comment]
I can also confirm this
